import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MdSearch, MdMenu } from "react-icons/md";
import Search from "@/app/ui/search";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="fixed z-[1000] bg-white w-full ">
                    <div className="flex  p-4 border-b justify-between">
                        <h1 className="font-bold text-lg"> Property App</h1>
                        <Search placeholder="Search properties..." />
                        <Link
                            href="/create"
                            type="button"
                            className=" bg-blue-900 text-white font-bold rounded-md hover:bg-navy-700 transition-all duration-150 ease-in-out active:scale-95 w-fit p-1"
                        >
                            Add Property
                        </Link>
                    </div>
                </div>
                {children}
            </body>
        </html>
    );
}
